### ISSUE TITLE
Use of custom buttons

### ISSUE THREAD

**Issue by grey280** [alexaubry/BulletinBoard#106]
Working on a custom subclass of `BLTNPageItem` that includes multiple buttons in the 'main button' style, and while I've got it working, I wanted to verify that the way I'm doing it is correct.
In one of the `makeViewsUnder...` methods, I'm creating a button, i.e. `let newActionButton = interfaceBuilder.makeActionButton...`
I'm then attaching the handler via `newActionButton.button.addTarget`.
Is this the correct way to respond to that button being tapped, or is there something else I should be doing?
Thanks!

**Comment by alexaubry** [comment]
Hi! It seems to be correct from what you're telling me 😄 Feel free to reopen an issue if you encounter any problem with that setup.

**Comment by NiroTheHero** [comment]
pretty old, but ill try anyway :)
Hi @grey280, would your solution for costume buttons lets you also costume the design of the buttons (e.g adjusting rounded corners, shadow etc etc)??

thanks

**Comment by grey280** [comment]
@NiroTheHero yeah, since I'm creating the button from scratch (or rather, in my implementation, I'm using `interfaceBuilder.makeActionButton`) it's available in code as a customizable view; I haven't actually done any visual customization in there, but it's certainly possible!
