### ISSUE TITLE
TextField ? 

### ISSUE THREAD

**Issue by turgutoztunc** [alexaubry/BulletinBoard#11]
Is it possible to put textfield instead of button ?

**Comment by alexaubry** [comment]
You technically can add a text field to the bulletin by creating a custom class that implements the `BulletinItem` protocol and return a text field in the `makeArrangedSubviews` method. See the implementation of [`PetSelectorBulletinPage`](https://github.com/alexaubry/BulletinBoard/blob/master/Example/Sources/PetSelectorBulletinPage.swift) for more guidance in creating a custom bulletin item.

However, the library does not handle adapting for the keyboard frame, so I am not sure this would look nice.

**Comment by alexaubry** [comment]
#12 implemented the keyboard frame update mechanism. You can now create a custom item with a text field, as mentioned in my previous comment.
