### ISSUE TITLE
UI Freezes after swiping bulletin and tapping close button

### ISSUE THREAD

**Issue by venom889** [alexaubry/BulletinBoard#129]
**Problem Description:**
Tapping on the close button after swiping upwards on the bulletin causes the UI to freeze. I believe this is an issue with the interactive pan gesture and the `dismissBulletin` method called by the close button.

**Steps to reproduce:**
1. Display a bulletin with `requiresCloseButton = true`.
2. Pan the bulletin controller upwards using the gesture. This is tricky but you basically need to pan while holding your finger down. Don't release the gesture.
3. Before releasing the window use your other finger to tap on the close button as many times as needed.
4. Release the finger being used to pan the controller.

**Result**
The bulletin UI will freeze completely. The close button, actions, gesture, background view, and all subviews in the bulletin controller will no longer handle touches.

**Expected Result**
The bulletin should be dismissed.

**Notes**
We've had some users come across this while swiping downwards over the area where the close button is. I think this is the same issue but I could not reproduce it reliably. 

**Environment:**
 - Device: iPhone XR
 - OS: iOS 12.0
 - Version of BulletinBoard: 2.0.2

**Comment by ddaddy** [comment]
I'm experiencing this issue too, but it's much simpler to replicate.

I'm launching a simple bulletin with this code:
```
- (IBAction)testShowBulletin
{
    BLTNPageItem *page = [[BLTNPageItem alloc] initWithTitle:@"Title"];
    page.descriptionText = @"Some text here";
    page.dismissable = YES;
    self.bulletinManager = [[BLTNItemManager alloc] initWithRootItem:page];
    [self.bulletinManager showBulletinAboveViewController:self animated:YES completion:NULL];
}
```

When it shows, if you swipe upwards on the bulletin the whole app freezes because the bulletin can no longer be dismissed. Tapping outside the bulletin does nothing as does the X close button.

**Comment by ddaddy** [comment]
I've found a way to stop this happening. If you set `self.bulletinManager.allowsSwipeInteraction = NO;` then it stop the bulletin moving if the user tries to swipe it upwards and the close button still works.

**Comment by a2** [comment]
I will look into this issue over the weekend. This is definitely affecting users in production and we want to solve this ASAP.

**Comment by a2** [comment]
Hi folks, I made a branch [here](
https://github.com/alexaubry/BulletinBoard/tree/fix/frozen-dismissal) with a potential fix. Can you verify in your own projects that the `fix/frozen-dismissal` branch fixes the issue? If so, I'll merge that into master and tag a new release.

---

You can configure your Podfile like this to test the branch:

```ruby
pod "BulletinBoard",
  :git => "https://github.com/alexaubry/BulletinBoard.git",
  :branch => "fix/frozen-dismissal"
```

Or your Cartfile like this:

```ogdl
github "alexaubry/BulletinBoard" "fix/frozen-dismissal"
```
