### ISSUE TITLE
Swipe to dimiss not triggering dismissalHandler

### ISSUE THREAD

**Issue by phchosis** [alexaubry/BulletinBoard#14]
When swiping to dismiss a PageBulletinItem, it dismisses correctly but does not trigger the dismissalHandler. The dismissalHandler works fine with tap to dismiss.

### New Issue Checklist
- [x] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Issue Description
After setting up a simple PageBulletinItem providing a title, descriptiontext, actionbuttontitle, alternativebuttontitle, setting isDismissable to TRUE as well as supplying an actionHandler and dismissalHandler. When presenting this item, tapping to dismiss triggers the dismissalHandler where as swiping does not.

![simple_bulletinmanager_with_item](https://user-images.githubusercontent.com/3295039/32276256-4a8a165c-bf06-11e7-9b4c-efa0095f6730.png)

### Environment

- **iOS Version**: iOS 11.0.3
- **Device(s)**: iPhone 6s

**Comment by phchosis** [comment]
Adding the following highlighted line seems to have resolved it

<img width="494" alt="screen shot 2017-11-01 at 14 54 01" src="https://user-images.githubusercontent.com/3295039/32280686-9914fe64-bf14-11e7-837c-ad7a0502122e.png">

**Comment by alexaubry** [comment]
Thank you for reporting, I'll be working on a fix.

**Comment by alexaubry** [comment]
I have tried to reproduce the issue, unsuccessfully. Could you please attach some sample code where the dismissalHandler is not called?

**Comment by alexaubry** [comment]
Maybe your `caputureSession` is nil when you swipe down, for some reason. Do you get a crash if you force unwrap it?

**Comment by phchosis** [comment]
@alexaubry Sure, Here is some code which is not triggering the dismissalHandler when swiped down.

    fileprivate func makeSharePage() -> PageBulletinItem {
        let page: PageBulletinItem = PageBulletinItem(title: "Share your Selfie")
        page.descriptionText = "Great Selfie, it's been saved to your photo library, why don't you share it online?"
        page.actionButtonTitle = "Share now"
        page.alternativeButtonTitle = "maybe later"
        page.isDismissable = true
        page.actionHandler = { item in
            print("actionHandler")
        }
        page.alternativeHandler = { item in
            item.manager?.dismissBulletin(animated: true)
        }
        page.dismissalHandler = { item in
            print("dismissalHandler")
        }
        return page
    }

**Comment by alexaubry** [comment]
There was a problem with the gesture recognizer: if the user scrolled too fast, the transition would not be marked as finished and the completion handler would not call `dismissalHandler`.

To fix this, the user now needs to lift their finger to dismiss the bulletin.

The fix is available on the `master` branch, would you mind trying it and tell me if your issue is solved?

**Comment by alexaubry** [comment]
This appears to be working consistently in the latest commits, closing this issue for now. Feel free to reopen it if you still have this bug 👍
