### ISSUE TITLE
iOS 8 support 

### ISSUE THREAD

**Issue by bizibizi** [alexaubry/BulletinBoard#150]
can you make it available since iOS 8? It requires only 2 lines to change in the code

**Comment by alexaubry** [comment]
Hello, thanks for your suggestion. I don't have any way to test it, so I'm not really inclined to adding iOS 8 support.

**Comment by bizibizi** [comment]
can i send you a pull request?

**Comment by n3d1117** [comment]
@bizibizi I'd be interested in iOS 8 support. Could you open a pull request or post the code changes needed here? Thanks
