### ISSUE TITLE
ActionButton dismiss problems: Attempt to present <> which is already presenting (null)

### ISSUE THREAD

**Issue by ttoni** [alexaubry/BulletinBoard#154]
**Problem Description:**
Warning: Attempt to present <BLTNBoard.BulletinViewController: 0x12a041e00>  on <XYZ: 0x12a931600> which is already presenting (null)

**Steps to reproduce:**
Dismissing by action button randomly triggers this warning and is not closing the dialog

**Environment:**
 - Device: iPhone 7+
 - OS: 12.2
 - Version of BulletinBoard: 3.0

**Comment by DK-Web** [comment]
I have the same issue. I use one Bulletinboard on first App start (works fine) and if this board is closed and i opened a second one for in app purchase first page presented, but all buttons are dead. Any idea? Thx 😊✌️
