### ISSUE TITLE
Add Swift Package Manager support

### ISSUE THREAD

**Issue by marekpridal** [alexaubry/BulletinBoard#158]
Swift PM is officially supported in Xcode 11 so it would be great if BulletinBoard supports it 🙂

**Comment by alexaubry** [comment]
I think it would be nice too! Unfortunately I don't think it supports embedding resources yet, so that will be tricky to support it since we need some images and strings.

**Comment by iWeslie** [comment]
As mentions in WWDC19 [session 410](https://developer.apple.com/videos/play/wwdc2019/410/?time=1780), SPM will soon support resources. So, when this [proposal](https://forums.swift.org/t/swift-pm-bundles-and-resources/13981/23) is adapted, we will be glad if you can add SPM support.

**Comment by iWeslie** [comment]
And, I think there is another option. `UIImage(systemNamed: "xmark")` to generate a x mark image from iOS 13 new API with SFSymbols. This may be a good way to remove unnecessary resources in BLTN.@alexaubry

**Comment by iWeslie** [comment]
Or use `UIGraphicsGetCurrentContext` in iOS12 and lower

**Comment by nathanhleung** [comment]
Looks like the proposal landed in Swift 5.3! https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md

**Comment by alexaubry** [comment]
I added a branch with SPM support: `feature/spm-support`. Can one of you please try it and let me know if something breaks?

**Comment by robergro** [comment]
Hey @alexaubry,
Thank you for adding SPM on your project :) 
With this new version (SPM installation), we no longer have access to the "appearance" variable on BLTNPageItem class.
Is this normal?

**Comment by alexaubry** [comment]
@robergro It should still be there, could you send the error from Xcode so I can have a look?

**Comment by robergro** [comment]
Of course, here it is !

<img width="1363" alt="Capture d’écran 2020-06-04 à 15 23 20" src="https://user-images.githubusercontent.com/6044208/83762130-7a378780-a677-11ea-9bb0-b12012275a47.png">

**Comment by alexaubry** [comment]
@robergro It should be fixed now, thanks for reporting! There were some issues with importing Objective-C from the package.

**Comment by rodmaz** [comment]
It seems Swift Package support for BulletinBoard is broken on Xcode 12:

`target at '/Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-ezhoowqbocgzhycfoojnfdfrulyf/SourcePackages/checkouts/BulletinBoard/Sources' contains mixed language source files; feature not supported`

**Comment by JonnyBeeGod** [comment]
> It seems Swift Package support for BulletinBoard is broken on Xcode 12:
> 
> `target at '/Users/xxx/Library/Developer/Xcode/DerivedData/MyApp-ezhoowqbocgzhycfoojnfdfrulyf/SourcePackages/checkouts/BulletinBoard/Sources' contains mixed language source files; feature not supported`

If you use the `feature/spm-support` branch it will work, had the same problem yesterday. Seems like it hasn't been merged yet.

**Comment by trevor-sonic** [comment]
I could only add ```SPM```  with ```develop``` branch. 
SPM is supporting assets now. There is no need to use other things like cocaopod or whatever

**Comment by alexaubry** [comment]
@trevor-sonic Please check out #189 for details

**Comment by alexaubry** [comment]
This is available in 5.0 now. Thanks for your patience!
