### ISSUE TITLE
UITextfield > PasswordField - secureTextEntry

### ISSUE THREAD

**Issue by DK-Web** [alexaubry/BulletinBoard#162]
Hi, can you please install the possibility that you can use textfields as password fields? 

Only this parameter is missing:
texfield.secureTextEntry = true

Thanks a lot!

**Comment by eliburke** [comment]
You can do this yourself.

 I don't know how you are adding your text field, but if you are calling _BLTNInterfaceBuilder.makeTextField()_ it returns the text field for direct access.

**Comment by DK-Web** [comment]
Hi, thank you! I did not know that I could use the textfield. With this change everything works perfectly. Thank you for your quick help!

`textField = interfaceBuilder.makeTextField(placeholder: "Password", returnKey: .done, delegate: self)
textField.isSecureTextEntry = true`
