### ISSUE TITLE
Alternativ Button Color

### ISSUE THREAD

**Issue by DK-Web** [alexaubry/BulletinBoard#163]
Hi, 
is there a way to change the text color of the alternative button? 

Thanks and best regards

**Comment by eliburke** [comment]
If you are using stock controls (e.g. setting alternativeButtonTitle, alternativeButtonHandler) you can modify BLTNItemAppearance in the BLTNPageItem constructor
````self.appearance.alternativeButtonTitleColor = UIColor.purple````

or you can do it in the presentation handler block:
````
        self.presentationHandler = { (_ item: BLTNItem) in
            // disable the set button until conditions are met
            self.alternativeButton?.isEnabled = false
        }
````

If you are using makeViewsUnderDescription or one of the other customization points, you can directly modify the buttons returned by _BLTNInterfaceBuilder.makeAlternativeButton_ (or _makeActionButton_)

There is a lot of good detail in the code and in some of the closed issues.

**Comment by DK-Web** [comment]
Thanks a lot! I was looking for it, but I'm still pretty new to app development, so I could not find the solution myself.
