### ISSUE TITLE
IOS 13 Dark Mode

### ISSUE THREAD

**Issue by DK-Web** [alexaubry/BulletinBoard#168]
Hi, thank you for your great BulletinBoard. Unfortunately, this is broken in IOS 13 in Darkmode, since e.g. the date picker is no longer visible, because the background of the bulletin board is not set by .systemBackground (white on white) Can you look at this please? Maybe you can set the backgrounds via .systemBackground and the font by .label.
Thank you and best regards

**Comment by DK-Web** [comment]
@alexaubry please we need a bugfix! Thx

**Comment by alexaubry** [comment]
Hey! I don’t have the bandwidth to look into this at the moment. If you have a fix, feel free to submit a PR :)

**Comment by chrisDeft** [comment]
You can set the backgroundColor property of the BLTN Item Manager to systemBackground - as long as you do this before showing a bulletin it seems to work fine in dark mode.

**Comment by aaronbrethorst** [comment]
I'm working on this.

**Comment by DK-Web** [comment]
> You can set the backgroundColor property of the BLTN Item Manager to systemBackground - as long as you do this before showing a bulletin it seems to work fine in dark mode.

Hi chrisDeft, a good note thank you! 
I solved the problem with 
`bulletinManager.backgroundColor = .systemBackground`

I could also change the font color of the pages like this:
```
page.appearance.descriptionTextColor = .label
page.appearance.titleTextColor = .label
```

**Comment by DK-Web** [comment]
> I'm working on this.

Hi aaronbrethorst, thank you for working on it! Best regards

**Comment by Danny-SS** [comment]
Thanks @aaronbrethorst! hoping this gets merged
