### ISSUE TITLE
CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: 'org.cocoapods.BLTNBoard'

### ISSUE THREAD

**Issue by alombard** [alexaubry/BulletinBoard#169]
When running on a physical device using Xcode 11 and iOS 13 I experience the following Error:  

RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: 'org.cocoapods.BLTNBoard'

It has the effect of not crashing the app but no Boards show.

Steps to repro:
Add the pod to the project.  Open using Xcode 11 and run on a physical device using IOS 13.

**Environment:**
 - Device: iPhone XS
 - OS: IOS 13
 - Version of BulletinBoard: 4.0.0

Any help is appreciated - I love this project but am currently not able to use it.

Cheers.

Andrew

**Comment by yusuftor** [comment]
I get the same warning! Except my boards still show.

**Comment by alombard** [comment]
Thanks @yusuftor - I'm suspicious that this is my bug then.  I'm going to take another look and confirm - this error may be a red herring.

**Comment by AveryVine** [comment]
Getting the exact same thing, error and no boards

**Comment by alombard** [comment]
Hi everyone - after close inspection this was a bug in my onboarding code and not an issue with the framework or the integration.

Thanks! 

Cheers,

Andrew
