### ISSUE TITLE
Swift Compiler Warning: Cannot match several associated values at once

### ISSUE THREAD

**Issue by BigDada1** [alexaubry/BulletinBoard#186]
**Problem Description:**
In [`BulletinBackgroundView`, L86](https://github.com/alexaubry/BulletinBoard/blob/5c28acbfc85328e5963f1f50d0399fac7829d457/Sources/Support/Views/Internal/BulletinBackgroundView.swift#L86) Xcode shows me a warning: _»Cannot match several associated values at once, implicitly tupling the associated values and trying to match that instead«_

**Steps to reproduce:**
- Checkout current example project
- Build
- Swift warning appears

**Environment:**
 - Xcode Version 11.6 (11E708)
 - Version of BulletinBoard: 4.1.2 via CocoaPods

**Comment by BigDada1** [comment]
The warning can be fixed by extracting the associated values:
`case .blurred(let style, true), .blurred(let style, false):`

**Comment by alexaubry** [comment]
Can you let me know if this is still an issue in the upcoming release? #189

**Comment by BigDada1** [comment]
Fixed in 5.0.0-rc1 👍🏻
