### ISSUE TITLE
Feature Request: Swipe down to dismiss when card is dismissable

### ISSUE THREAD

**Issue by Oyveloper** [alexaubry/BulletinBoard#2]
### New Issue Checklist
- [x] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Issue Description

When the isDismissable property is set to true you can touch outside of the card to dismiss, but I think you should also be able to swipe the card down with a gesture as well. 

### Environment

- **iOS Version**: [iOS 11]
- **Device(s)**: [iPhone X]

**Comment by alexaubry** [comment]
Thanks for the suggestion, I'll be working on it 👍

**Comment by alexaubry** [comment]
This feature was implemented in cff1d2dfbbc6605d9af76a7ca7cb5adf8b77e26f and will be available in the next release.
