### ISSUE TITLE
How to add textfield ?

### ISSUE THREAD

**Issue by nyto9999** [alexaubry/BulletinBoard#203]
```    private lazy var boardManager: BLTNItemManager = {
        let item = BLTNPageItem(title: "Create Post")
        item.image = UIImage(systemName: "square.and.pencil")
        **I want to have a textfield here thanks**
        item.actionButtonTitle = "Post"
        item.descriptionText = "would you like to post?"
        item.actionHandler = { _ in
            MainViewController.didTapBoardContinue()
        }
        item.alternativeHandler = { _ in
            MainViewController.didTapBoardSkip()
        }
        return BLTNItemManager(rootItem: item)
    }()
```

**Comment by CQuerido** [comment]
Hello, I'm looking for exactly the same possibility did you find the solution ?

**Comment by nyto9999** [comment]
nope, I give up

**Comment by eliburke** [comment]
This can be seen in the Example project:
https://github.com/alexisakers/BulletinBoard/blob/develop/Example/CustomBulletins/TextFieldBulletinPage.swift

It is also discussed in a couple of closed issues:
https://github.com/alexisakers/BulletinBoard/issues/32#issuecomment-398862998
https://github.com/alexisakers/BulletinBoard/issues/162
