### ISSUE TITLE
Could not find module 'BLTNBoard' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: .../Build/Products/Debug-iphonesimulator/BLTNBoard.swiftmodule

### ISSUE THREAD

**Issue by neobeppe** [alexaubry/BulletinBoard#206]
**Problem Description:**
BLTNBoard not building on simulator with M1 Mac 

**Steps to reproduce:**
On M1 Mac try to build project importing BLTNBoard via SPM

**Environment:**
 - Device: Simulator
 - Version of BulletinBoard: 5.0.0

**Comment by ilkerc** [comment]
Thats not related with this repository. But here is an ultimate guide about that :)

I think you also use CocoaPods and some of your dependencies may exclude arm64 architectures or marks x86_64 as the only valid architecture on simulator.

```
EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64
or
VALID_ARCHS[sdk=iphonesimulator*] = x86_64
```

you can search your dependencies pod specs with: `pod spec cat AppLovinSDK`

<img width="446" alt="Screen Shot 2022-02-03 at 22 28 44" src="https://user-images.githubusercontent.com/6921843/152415019-63925c5a-ae08-473d-8fb9-eb264d3869af.png">
or  `pod spec cat TikTokOpenSDK`
<img width="394" alt="Screen Shot 2022-02-03 at 22 29 14" src="https://user-images.githubusercontent.com/6921843/152415081-7a421fe5-2974-4d46-a5d0-8ae3aa0e6f9d.png">

If this is valid than xCode does compiles your dependencies with x86_64 arch (which forces your simulator to launch on top of rosetta2), in other words; you're running your simulator apps with rosetta2 support. Unfortunately you can't tell SPM which archs to exclude. You have two options here;

* Be sure that all your static cocoapods dependencies support for arm64-sim slices.
* just use cocoapods, it will exclude arm64 and compile with x86_64 support.
