### ISSUE TITLE
Expose BulletinManager.viewController.contentView

### ISSUE THREAD

**Issue by jyounus** [alexaubry/BulletinBoard#21]
It would be great if we could have the contentView exposed, something like this inside the BulletinManager class:

```
public func getContentView() -> UIView {
    return viewController.contentView
}
```

For my use case, this would be to add some UIMotionEffects to the contentView. Rather than making this part of the lib, it would be better to just simply expose the contentView so devs can handle such customisations themselves.

I can make a PR if you're happy with this change (or feel free to add it yourself in your next commit).

**Comment by alexaubry** [comment]
I added a way to perform an operation with the content view:

~~~swift
bulletinManager.withContentView {
    $0.addMotionEffect(...)
}
~~~

This will be available in the next release. You can build from the master branch to try it now 😃
