### ISSUE TITLE
Uncheck Gather Coverage Data

### ISSUE THREAD

**Issue by CocoaPriest** [alexaubry/BulletinBoard#22]
When using Carthage [static frameworks], the linker fails. Simply unchecking `Gather Coverage Data` in BulletinBoard's test scheme fixes this issue.

**Comment by alexaubry** [comment]
Could you please tell me if building from the master branch works now?

**Comment by alexaubry** [comment]
Building BulletinBoard as a static framework appears to work when I follow Carthage's [guide](https://github.com/Carthage/Carthage/blob/master/Documentation/StaticFrameworks.md). Feel free to reopen the issue if that didn't fix it for you.
