### ISSUE TITLE
Bulleting Appearance not available

### ISSUE THREAD

**Issue by Eliaschetouani** [alexaubry/BulletinBoard#27]
Hello !

Is not available in the master branch :/ 

Thank you

**Comment by alexaubry** [comment]
### If you are using Carthage

Make sure to use this in your Cartfile:

~~~
github "alexaubry/BulletinBoard" "master"
~~~

And then run `carthage update` to build the latest version.

### If you are using CocoaPods

Make sure you are using this in your Podfile:

~~~ruby
pod 'BulletinBoard', :git => 'https://github.com/alexaubry/BulletinBoard.git', :branch => 'master'
~~~

And then run `pod install` and `pod update` to make sure you get the latest version.

Tell me if you need more help 😃

**Comment by alexaubry** [comment]
It appears to be working with the two snippets I provided. Feel free to reopen the issue if it still does not work.

**Comment by Capossito** [comment]
im getting the same issue there's no appearance available for the PageBulletinItem. I'm on the latest version 1.3.0, and still not working. already pulled directly from master but still. help please.

**Comment by yusuftor** [comment]
+1

**Comment by alexaubry** [comment]
@Capossito @yusuftor Could you try using the 2.0.0 beta and let me know if the appearance is available with this version?

**Comment by yusuftor** [comment]
Will do, can I do this through Cocoapods?

**Comment by alexaubry** [comment]
Sure, try using the `v2` branch in your Podfile:

~~~ruby
pod 'BulletinBoard', :git => 'https://github.com/alexaubry/BulletinBoard.git', :branch => 'v2'
~~~

**Comment by yusuftor** [comment]
Ok just tried and it doesn't work with that either. It works in the sample swift app though...

**Comment by yusuftor** [comment]
Hi, just tried this again today. The master branch **does** work with appearance. I think it was an issue with Cocoapods so I've been cleaning my project and closing and reopening it. Finally it works! Thank you.
