### ISSUE TITLE
Use of unresolved identififer 'HighlightButton'

### ISSUE THREAD

**Issue by rossrossp** [alexaubry/BulletinBoard#28]
We've got some issues with the latest master:
![screen shot 2017-11-21 at 12 04 46](https://user-images.githubusercontent.com/6325131/33071729-a6dc5b6e-ceb4-11e7-9604-5d08cce1af93.png)

**Comment by alexaubry** [comment]
You can't not use the HighlightButton type directly, as it's an implementation detail of BulletinBoard, and is hidden to apps to avoid animation issues when using it inside bulletin items. 

However, if you update to the latest master (after 1c7243bbc0cd0842e51e62aaa80bffbb71d3b43f), you can use the following code:

~~~swift
public func makeInfoButton() -> HighlightButtonWrapper {

    let wrapper = HighlightButtonWrapper()
    let infoButton = wrapper.button 

    infoButton.setImage(UIImage(named: "icon-calendar-single-remove"), for: .normal)

    infoButton.contentHorizontalAlignment = .center
    infoButton.contentVerticalAlignment = .top
    infoButton.autoresizingMask = .flexibleWidth

    wrapper.setContentHuggingPriority(UILayoutPriorityDefaultLow, for: .horizontal)
    wrapper.heightAnchor.constraint(equalToConstant: 44).isActive = true

    return wrapper

~~~

(P.S. Sorry for the delay 😬)

**Comment by alexaubry** [comment]
Closing this issue for now. Feel free to reopen it if you still need help.
