### ISSUE TITLE
Hide status bar

### ISSUE THREAD

**Issue by MickaelCruzDB** [alexaubry/BulletinBoard#29]
Hi! I need to hide the status bar of my bulletins (no statusbar on my app). In my BulletinDataSource I added :
```
var prefersStatusBarHidden: Bool {
            get {
                return true
            }
}
```
However it doesn't change nothing, status bar appears as soon as the bulletin is displayed. Any idea? Thanks!

**Comment by alexaubry** [comment]
I've added a new status bar customization API in the latest master commit (9075e50bed439b4ed1f14ff096d7143d60ff9431).

To hide the status bar, you can now use this:

~~~swift
bulletinManager.statusBarAppearance = .hidden
bulletinManager.prepare()
~~~

Note that you have to change the `statusBarAppearance` before calling `prepare` and presenting the bulletin.

This will ship with the next release, but you can build the framework from the master branch if you need this new feature today. Thanks for this good suggestion!
