### ISSUE TITLE
Display bulletin over tab bar

### ISSUE THREAD

**Issue by MarcoCarnevali** [alexaubry/BulletinBoard#30]
Hello! I think it's better to replace this:
( on presentBulletin func on BulletinManager ) 
` presentingVC.present(viewController, animated: animated, completion: completion)`
with:
`if let tabBar = presentingVC.tabBarController {
            tabBar.present(viewController, animated: animated, completion: completion)
        }else{
            presentingVC.present(viewController, animated: animated, completion: completion)
        }`

Like this, if the tabBar is present, it shows over it.

Thank you

**Comment by alexaubry** [comment]
You can already do this yourself, by telling the bulletin manager above which view controller the bulletin should be presented.

You can present the bulletin over your tab bar by using this code:

~~~swift
bulletinManager.presentBulletin(above: tabBarController ?? self, animated: true, completion: nil)
~~~

It presents your bulletin above the view controller's tab bar controller, or over the view controller if it does not have a tab bar controller.

Let me know if this works 😃

**Comment by alexaubry** [comment]
I'm using this solution in production, and it appears to be working fine. Feel free to reopen this issue if you expected another result.
