### ISSUE TITLE
Customizing the stock PageBulletinItem

### ISSUE THREAD

**Issue by eliburke** [alexaubry/BulletinBoard#32]
For my app, I wanted to customize the stock PageBulletinItem class with additional views so that we have a consistent look and feel between stock and modified Pages. Unfortunately, some parts of PageBulletinItem are _public_ instead of _open_ and can't be overridden, and the stack view of buttons is not available outside of makeArrangedSubviews(). 

Do you have any interest in exposing additional customization, and/or would you accept a PR for such a feature? I think it could be done cleanly with either additional function variables (like actionHandler), optional protocol funcs,  or override-able funcs in PageBulletinItem. These customization points would be called inside PageBulletinItem.makeArrangedSubviews(). Example:
`open func viewsAboveTitle(_ interfaceBuilder: BulletinInterfaceBuilder) -> [UIView]`
and so on for the "space" before and after each element: | title | image | description | buttons |

Here's an example I made with a local copy of PageBulletinItem. 
<img width="384" alt="screen shot 2017-11-30 at 4 12 43 pm" src="https://user-images.githubusercontent.com/2371768/33455904-87b3dddc-d5eb-11e7-9b02-2bd3a60761ba.png">

````
class TextFieldPageBulletinItem: CustomizedPageBulletinItem {
    
    fileprivate var errorLabel: UILabel?
    fileprivate var textField: UITextField?
    public var textInputHandler: ((_ text: String) -> Void)?
    
    override func makeArrangedSubviews() -> [UIView] {
        var arrangedSubviews = super.makeArrangedSubviews()
        
        let interfaceBuilder = InterfaceBuilderType.init(appearance: appearance)
        errorLabel = interfaceBuilder.makeDescriptionLabel()
        errorLabel!.text = ""
        errorLabel!.textColor = .red
        
        textField = UITextField()
        textField!.delegate = self
        textField!.borderStyle = .roundedRect
        textField!.returnKeyType = .done
        
        // find the optional stack view of buttons and insert above it
        var buttonStack: UIStackView?
        for view in arrangedSubviews {
            if let bs = view as? UIStackView {
                buttonStack = bs
                break
            }
        }
        if let buttonStack = buttonStack, let idx = arrangedSubviews.index(of: buttonStack) {
            // insert in reverse order
            arrangedSubviews.insert(textField!, at: idx)
            arrangedSubviews.insert(errorLabel!, at: idx)
        } else {
            // insert in correct order
            arrangedSubviews.append(errorLabel!)
            arrangedSubviews.append(textField!)
        }
        
        // since there isn't a method similar to "viewDidAppear" for BulletinItems,
        // we're using a workaround open the keyboard after a certain amount of time has elapsed
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) { [weak self] in
            self?.textField?.becomeFirstResponder()
        }
        return arrangedSubviews
    }
}

extension TextFieldPageBulletinItem: UITextFieldDelegate {
    func isInputValid(text: String?) -> Bool {
        if text != nil && !text!.isEmpty {
             return true
        }
         return false
    }
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        if let text = textField.text, isInputValid(text: text) {
            textField.resignFirstResponder()
            textInputHandler?(text)
            return true
        } else {
            errorLabel?.text = "You must enter some text to continue."
            textField.backgroundColor = .red
            return false
        }
    }
}
````

**Comment by alexaubry** [comment]
That's definitely an important missing feature. Thanks for requesting it!

I've been testing several ways to implement it, and I've pushed what I think is the easiest solution on the master branch (f8f765753fd0d97462a19d63ab3ab58e3268bdf4).

I've created a base class `ActionBulletinItem` that handles creating the buttons and recognizing the taps. It has an `open` method named `makeContentViews(interfaceBuilder:)` that you can override to return the elements displayed above the buttons. `PageBulletinItem` builds on top of this class now.

@eliburke You can check out the git diff of the commit to see how it makes creating custom items with buttons easier and more flexible.  Tell me if you think more customization is needed.

**Comment by eliburke** [comment]
@alexaubry this is interesting. It's pretty different than what I was thinking. Customizing custom Bulletins that look like PageBulletinItem will still take a fair bit of boilerplate, but it is manageable. Customizing the buttons as in PetSelectorBulletinPage is weighty. 

For kicks, I tried updating TextFieldBulletinPage to use ActionBulletinItem. It is unfortunately difficult to get the text input out cleanly with the existing API. See #35

I know it would be a departure from the current API, but what do you think about changing the actionHandler/altActionHandler to call a single closure with an enum and perhaps associated data?

**Comment by eliburke** [comment]
FWIW, I don't mean to sound negative about this update. It's a great improvement for modifying the stock appearance and using the standard button behavior, and also makes implementing a completely custom design much cleaner.

**Comment by alexaubry** [comment]
@eliburke Thank you very much for you feedback! I've implemented your initial suggestion in PR #41, and it makes customization way easier and reduces the amount of boilerplate code 💯

Can I ask you to review the PR and tell me if you think some improvements are still needed?

**Comment by alexaubry** [comment]
I will open a separate issue about callback changes for actionHandler/altActionHandler.

**Comment by eliburke** [comment]
Hi @alexaubry I'm happy to take a look. Do you want me to do a full PR review (which I think you have to initiate?) or just let you know what I think?

**Comment by eliburke** [comment]
Couple of things I've noticed:
footerViews() is not being called by ActionBulletinItem.makeContentViews()

There is a bug in BulletinInterfaceBuilder.makeTextField(). It does not honor the returnKey parameter but rather hard codes it to .default.

**Comment by alexaubry** [comment]
Thanks for the feedback! I fixed the returnKey parameter bug.

I'm actually calling `footerViews()` after `makeContentViews()`, so I think it's good.

https://github.com/alexaubry/BulletinBoard/blob/eba896d2d33126f307b96d7f6dcaf10c8710a068/Sources/Models/ActionBulletinItem.swift#L247

Please let me know if you think other customisation options are missing for the page item, or if you think there are enough now 😄

**Comment by alexaubry** [comment]
I thought `headerViews` made more sense in PageBulletinItem, because it has a title.

**Comment by alexaubry** [comment]
These changes are now in the `master` branch and will ship with the next release. Thank you very much for the feature request and your help to implement it 💯

**Comment by gerbil802** [comment]
Hi, in relation to this- is there a textField ready page out of the box? or should I build I myself?

**Comment by eliburke** [comment]
You have to create it your self. But it's easy. This should be enough to get you started. ( I stripped a bunch of stuff out of some live code so I won't guarantee it compiles. 😄 )

```
class GerbilPageItem: BLTNPageItem {

    public private(set) var textField: UITextField!

    override init(title: String) {
        super.init(title: "Title")
         self.descriptionText = "Description"
         self.actionButtonTitle = "Ok"
         self.isDismissable = true
         self.alternativeButtonTitle = "Cancel"

        self.presentationHandler = { (_ item: BLTNItem) in
            self.textField?.becomeFirstResponder() // open the keyboard  
        }
    
    override func makeViewsUnderDescription(with interfaceBuilder: BLTNInterfaceBuilder) -> [UIView]? {
        var contentViews = [UIView]()
        
            let textField = interfaceBuilder.makeTextField(delegate: self)
            textField.returnKeyType = .done
            textField.spellCheckingType = .no
            textField.autocorrectionType = .no
            textField.autocapitalizationType = .none
            textField.placeholder = "username"
            textField.addTarget(self, action: #selector(textFieldDidChange), for: .editingChanged)
            contentViews.append(textField)
            self.textField = textField
        
        return contentViews
    }
}

extension GerbilPageItem: UITextFieldDelegate {
    
    @objc func textFieldDidChange(textField: UITextField) {
        textField.text = textField.text?.lowercased()
       // actionButton?.isEnabled = textField.text?.trim().isValidUsername() ?? false
    }
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        if let text = textField.text, text.isEmpty == false {
            textField.resignFirstResponder()
            return true
        } else {
            textField.backgroundColor = .red
            return false
        }
    }
}

```
