### ISSUE TITLE
Card and iPhone Safe Area

### ISSUE THREAD

**Issue by AAAstorga** [alexaubry/BulletinBoard#34]
### New Issue Checklist

- [x] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Issue Description

![img_9718](https://user-images.githubusercontent.com/15990084/33531259-6a178f66-d858-11e7-8ac9-dac77ed905ed.jpeg)
![img_9717](https://user-images.githubusercontent.com/15990084/33531260-6ccaa108-d858-11e7-8609-f823dc70364d.jpeg)

If the bulletin is not dismissible, but you move the card to the iPhone safe area, it will not reset to the proper position.

### Environment

- **iOS Version**: [INSERT iOS VERSION HERE]
- **Device(s)**: iPhone X

**Comment by alexaubry** [comment]
The fix for this branch is now in the master branch, and will ship with the next release. Thank you very much for reporting! 😄
