### ISSUE TITLE
Port to React-Native

### ISSUE THREAD

**Issue by Burnsy** [alexaubry/BulletinBoard#43]
Hello All, 

I don't know if any of you are interested, But I have started work on a port over to react-native!

Is this something you guys would be interested in? 

Thanks

**Comment by alexaubry** [comment]
Hello! I'm not familiar with React Native at all 😅 Could you please explain how the port would work?

**Comment by Burnsy** [comment]
Sorry for the delay Christmas and all that! Basically, a port would involve the two parts, swift code and javascript code, (I can code the javascript but my swift skills lack a little). the bridge would look for actions and when the actions are clicked on the javascript side they are sent through the bridge to native swift code, hence the code would open the given bulletin boards. Here a default tutorial [here](https://facebook.github.io/react-native/docs/native-modules-ios.html) 
![jsdc-2015-reactnative-23-638](https://user-images.githubusercontent.com/15834048/34327749-a9fc0586-e8c4-11e7-9ba3-af8e4184506f.jpg)

I can create the javascript side I would just need help connecting the bridge to the bulletin board functions. I have a local repo at my office that is all set up and the only code to be written is the bridge in theory.

If you like the sounds of this idea, I would love to work with you on it!

**Comment by everdrone** [comment]
Would love to see this ported to React Native!

**Comment by alexaubry** [comment]
Thank you folks for your input! I think this repository should focus on the core parts of the framework. The right approach would be to have a separate repository for the bridge, if someone wants to work on it. I'm closing this issue for now, let me know if someone decides to implement this!
