### ISSUE TITLE
iOS 11 devices treated as rounded corners

### ISSUE THREAD

**Issue by CaliCastle** [alexaubry/BulletinBoard#45]
### New Issue Checklist

- [x] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Issue Description

<b>iPhone 7 iOS 11.2:</b>
<img width="427" alt="messages image 1992398790" src="https://user-images.githubusercontent.com/10830749/34310046-1932b9ca-e70a-11e7-912a-bab1566355bf.png">
<b>iPhone 8 Plus iOS 11.2:</b>
<img width="696" alt="messages image 573817002" src="https://user-images.githubusercontent.com/10830749/34309952-9128ed74-e709-11e7-8e53-a6b6d6e8e5b6.png">

I do not think the condition failed even when it's not iPhone X that doesn't have rounded corners. Because in iOS 11 they are all under safe area so `screenHasRoundedCorners` will always be true in iOS 11+

```swift
@available(iOS 11.0, *)
    fileprivate var screenHasRoundedCorners: Bool {
        let insets = view.safeAreaInsets
        return (insets.top > 0) || (insets.bottom > 0)
    }
```
seems to fix the problem, I'm working on a commit

### Environment

- **iOS Version**: iOS 11
- **Device(s)**: iPhone 8 Plus, iPhone 7, iPhone SE

**Comment by alexaubry** [comment]
This was fixed in commit 9ad27f5e1f3a32ac635c7de69720fa7a6a8ea04a. Thank you for reporting!
