### ISSUE TITLE
Swift 3.2 Support not working

### ISSUE THREAD

**Issue by hassanmah** [alexaubry/BulletinBoard#5]
@alexaubry BulletinBoard is still not working on 3.2, I still get the same errors as I described on Twitter.

Furthermore, see the screenshot of Issue Navigator.

Thanks

<img width="379" alt="screen shot 2017-10-06 at 13 48 05" src="https://user-images.githubusercontent.com/3025707/31278578-60fe252c-aa9d-11e7-9f26-f3ef4aa523e4.png">

**Comment by alexaubry** [comment]
My bad, I had some trouble pushing the updated Podspec to CocoaPods. Make sure to call `pod update` again to update to 1.2.0.

**Comment by hassanmah** [comment]
@alexaubry `pod update` solves this
