### ISSUE TITLE
Pod File doesn't contain all source

### ISSUE THREAD

**Issue by khoogheem** [alexaubry/BulletinBoard#52]
Looks like when using the PodFile it doesn't contain all of the source.

Missing:

ActionBulletinItem.swift
BulletinAppearance.swift
BulletinInterfaceBuilder.swift
BulletinPadding.swift
AnimationChain.swift

**Comment by petritzdesigns** [comment]
Same problem for me. Using Cocoapod and downloaded the Version 1.3.0. 
The checksum is:
  BulletinBoard: 23c9d98cac654fd484d76f2a0655669974e9bd9c

**Comment by petritzdesigns** [comment]
Nevermind, this is because the current version in the master branch is ahead of the v1.3.0

**Comment by alexaubry** [comment]
If you need one of these features, you can use the `2.0.0-beta.1` prerelease.
