### ISSUE TITLE
Custom View Alignment

### ISSUE THREAD

**Issue by azhararmar** [alexaubry/BulletinBoard#57]
Align Custom Views Using Contraint

### New Issue Checklist

- [x] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Issue Description
I am using this library https://github.com/evgenyneu/Cosmos and I want to display it below the title, basically I am trying to achieve something similar to below screen (ignore the close icon)

![card](https://user-images.githubusercontent.com/10097624/35972180-cc0f7cb0-0cf6-11e8-8e7e-54573fc28580.png)

I created a custom page item class extending BulletinItem for this purpose

```
open class ReviewBulletinItem: BulletinItem {

    public weak var manager: BulletinManager?
    public var isDismissable: Bool = true
    public var dismissalHandler: ((BulletinItem) -> Void)?
    public var nextItem: BulletinItem?
    private let title: String = "ADD REVIEW"
    private let grade: Double = 3.6

    public func makeArrangedSubviews() -> [UIView] {
        // Init Sub Views
        var arrangedSubviews = [UIView]()
        let titleLabel: UILabel = self.makeTitleLabel(reading: self.title)
        let starRating: CosmosView = self.makeStarRating(withGrade: self.grade)
        // Add Sub Views
        for subView in [titleLabel, starRating] {
            arrangedSubviews.append(subView)
        }
        return arrangedSubviews
    }

    private func makeTitleLabel(reading title: String) -> UILabel {
        let titleLabel = UILabel()
        titleLabel.textAlignment = .center
        titleLabel.textColor = UIColor(hex: "#000000")
        titleLabel.accessibilityTraits |= UIAccessibilityTraitHeader
        titleLabel.numberOfLines = 1
        titleLabel.adjustsFontSizeToFitWidth = true
        titleLabel.font = UIFontLocalized(englishFontSize: 18.0, arabicFontSize: 18.0)
        titleLabel.text = title.uppercased()
        return titleLabel
    }
    
    private func makeStarRating(withGrade grade: Double) -> CosmosView {
        let ratingView = CosmosView()
        ratingView.backgroundColor = .red
        ratingView.rating = grade
        ratingView.settings.starSize = 18.0
        ratingView.settings.starMargin = 2.0
        ratingView.settings.fillMode = .precise
        ratingView.settings.filledImage = UIImage(named: "palm-tree-full")
        ratingView.settings.emptyImage = UIImage(named: "palm-tree-empty")
        ratingView.translatesAutoresizingMaskIntoConstraints = false
        ratingView.widthAnchor.constraint(equalToConstant: 128).isActive = true
        return ratingView
    }

    public func tearDown() {
        print("tearDown")
    }
}
```
The issue is, the star rating takes the full width screen and align left of the screen, whereas I want it in the center. PFA the screnshot

![review](https://user-images.githubusercontent.com/10097624/35972629-aaa89046-0cf8-11e8-839b-5bee18b5e3ed.png)

How do we align this view to the center? I tried applying constraints to ratingView and it does not seem to work.

### Environment

- **iOS Version**: 9.0
- **Device(s)**: 6s, 7, 8

**Comment by eliburke** [comment]
@azhararmar I have not tested this exact scenario, but I think if you create an empty UIView and then add your StarView as a subview, you will be able to apply constraints to the StarView to center it within the parent UIView. Then return the parent UIView to BulletinBoard, and when it is stretched to fill the screen width the StarView will remain centered.

**Comment by azhararmar** [comment]
@eliburke this makes sense, ill try this approach, thank you for your response. I appreciate it.

**Comment by alexaubry** [comment]
I will close this issue for now. Please feel free to create a new ticket if you still encounter a problem.
