### ISSUE TITLE
Multiple Pages

### ISSUE THREAD

**Issue by cesaredecal** [alexaubry/BulletinBoard#59]
So if I wanted to display two different pages which are not related to each other and should be displayed at different times would I need to create two bulletin managers? The thing is that I could only use one manager but then I'd have to hide the first page very quickly to show the `nextPage`.

**Comment by LowKostKustomz** [comment]
Probably yes.

You can create new manager with another root item or just push another item without back button to existing manager. All depends on your requirements.

**Comment by cesaredecal** [comment]
Awesome, thanks for helping out! Closing this.
