### ISSUE TITLE
App Store issue with NFC tags

### ISSUE THREAD

**Issue by cesaredecal** [alexaubry/BulletinBoard#60]
In the README it is stated that this library supports NFC tags. I'm getting an error from iTunes Connect saying that I need to specify that since I am using `NSBluetoothPeripheralUsageDescription` inside my app I have to specify the reason in the .plist file. Now, the issue is that I am not using NFC/Bluetooth. What I did was installing the pod plus duplicating every file in the example project. 

Do you think this issue is in some way related to this library? (It's one of the few libraries I am using) – is there also any way to disable NFC tagging? Thanks!

**Comment by LowKostKustomz** [comment]
The README says that bulletin board **looks** the same as cards displayed for NFC tag scanning and some other cards. The library does not provide any other features but presenting bulletin items, just UI.

> It **has an interface similar to the cards displayed by iOS for** AirPods, Apple TV configuration and **NFC tag scanning**.

Probably you have enabled NFC tags in your project file 

> Project file -> Your target -> Capabilities -> Near Field Communication Tag Reading

or another framework somehow uses it.

**Comment by cesaredecal** [comment]
Thanks so much! I can confirm the framework is NOT the cause of the issue.
