### ISSUE TITLE
adding "bulletinWillAppear/DidAppear" 

### ISSUE THREAD

**Issue by eliburke** [alexaubry/BulletinBoard#62]
I would like to be able to interact with my bulletin pages after they are shown to the user. For example: setting the first responder in order to show the keyboard, or disabling a button until a user has taken some other action. Right now it is only possible to do this via asyncAfter or a timer. 

I know that it is possible to pass a completion block to BulletinManager.presentBulletin(), but it does not have easy access to a bulletin's internal members. 

What do you think about adding an override-able method to BulletinIem that is called from BulletinManager.refreshCurrentItemInterface()? I'm not sure whether it would be better to call before the "Animate transition" or added to the transitionAnimationChain, but either one would be a good start.

**Comment by CaliCastle** [comment]
Hi, I added this for when the bulletin appeared, see if this can help you:
#47 
https://github.com/alexaubry/BulletinBoard/pull/47

**Comment by alexaubry** [comment]
This feature shipped with the version `2.0.0-beta.3` of the library. You now can set a `presentationHandler` and a `dismissalHandler` on the item to handle these events. These are called during the transition in `BLTNManager`.

Thanks again for your suggestion!

**Comment by MEnnabah** [comment]
@alexaubry is there a way to set a dismissal handler on the `BLTNItemManager` itself, so it get called when the `bulletinController` is dismissed? 
It would be helpful to do some task only once with bulletinController, instead handling each case with each item..

Thank you
