### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by st34m3dr1c3** [alexaubry/BulletinBoard#65]
Will this library be available for manual installation (not using CocoaPods/Carthage) in the future?

**Comment by alexaubry** [comment]
You can already install the library manually. All you have to do is cloning or downloading the repository and copying the `Sources` directory into your project (you can rename it, it doesn't matter).

If you've already done this and there were problems, let me know.

**Comment by alexaubry** [comment]
This should not be a problem. Do not hesitate to reopen the issue if you still encounter an issue.
