### ISSUE TITLE
Presenting a  ViewController above BulletinBoard

### ISSUE THREAD

**Issue by adeeldb** [alexaubry/BulletinBoard#66]
### New Issue Checklist

- [x] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Issue Description
I'm unable to present any view controller above the BulletinBoard. In the past version, there used to be the presentAboveBulletin() function in BulletinManager. However, it is not available anymore.

### Environment

- **iOS Version**: 11.1.2
- **Device(s)**: iPhone 7 Plus
- **BulletinBoard Version**: 2.0.0-beta-1

**Comment by alexaubry** [comment]
This feature shipped in `2.0.0-beta.3`. Thanks again for the feature request 😄
