### ISSUE TITLE
Value of type 'BulletinManager' has no member 'displayNextItem'

### ISSUE THREAD

**Issue by cyrilzakka** [alexaubry/BulletinBoard#69]
Can't seem to present the next item...

### New Issue Checklist

- [x] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Issue Description
Can't seem to present the next item... Method isn't there when checking files in the Pod.

### Environment

- **iOS Version**: [INSERT iOS VERSION HERE]
- **Device(s)**: [INSERT DEVICE(S) HERE]

**Comment by alexaubry** [comment]
What version of the library are you using?

**Comment by cyrilzakka** [comment]
Latest! Turns out it page.displayNext() not ItemManager you call .displayNext() on.
