### ISSUE TITLE
Adjust the blurring of the covered view

### ISSUE THREAD

**Issue by gregoireLem** [alexaubry/BulletinBoard#7]
Hey guys, thanks for this beautiful lib, 

Is there a way to easely manage the blurring of the covered view ?

thanks

**Comment by alexaubry** [comment]
This was implemented in #8 and will be included in the next release. Thank you for this suggestion 👍

**Comment by gregoireLem** [comment]
It would be great to have an option for no effect applied on the covered view too, in my case, I really need to display what is happening on the covered view

**Comment by alexaubry** [comment]
This feature shipped in v1.3.0.
