### ISSUE TITLE
code in textInputHandler run twice

### ISSUE THREAD

**Issue by MrShafiee** [alexaubry/BulletinBoard#72]
### Issue Description
Hi, when I print text in textInputHandler, it print twice in console log! what should I do ?
page.textInputHandler = { (item, text) in
               print("value is \(text)")
        }

**Comment by alexaubry** [comment]
Hi, I just managed to reproduce the issue. I will investigate.

**Comment by alexaubry** [comment]
I have fixed this issue. It turns out there were some issues in the handling of the return key and action button. The fix will be available in the next release, thanks very much for reporting! 😄

**Comment by alexaubry** [comment]
The fix shipped in `2.0.0-beta.3`.
