### ISSUE TITLE
Currently impossible to handle user input

### ISSUE THREAD

**Issue by ajchili** [alexaubry/BulletinBoard#73]
I have an issue with custom BulletinItems, if any contain UITextFields, it is impossible for a user on a physical device to provide input and see what they are typing. I have created a work around, however, I think it would be best to have an implemented feature for this.

I am not super familiar with swift conventions or best practices, but here is my current work around (function in BullitenManager.swift):
```swift
public func moveView(position: CGFloat) {
        if position != 0 {
            self.viewController.view.frame.origin.y -= position
        } else {
            self.viewController.view.frame.origin.y = 0
        }
}
```

**Before**
<img src="https://user-images.githubusercontent.com/7911799/39878944-949e9016-5447-11e8-850c-0edbf60d96e1.png" width="300"/>
**After**
<img src="https://user-images.githubusercontent.com/7911799/39879272-666cb6a4-5448-11e8-8f90-463a1ea8071f.png" width="300"/>

I can make a fork and PR but I just saw a new version was being worked on and I am unsure of your workflow. Any help/feedback would be greatly appreciated!

**Comment by alexaubry** [comment]
Which version of the framework are you using? Keyboard support was introduced in the first beta of 2.0.0. Switching to this version should fix this issue; although let me know if this is not the case 😃

**Comment by alexaubry** [comment]
The stable version of v2.0.0 shipped this morning, with text input support. You can upgrade according to the instructions in the release notes. This should fix your issue :)
