### ISSUE TITLE
unable to present bulletin from viewdidload

### ISSUE THREAD

**Issue by naman17** [alexaubry/BulletinBoard#74]
### New Issue Checklist

- [x] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Issue Description

this is my viewDidLoad() function:

    override func viewDidLoad() {
        super.viewDidLoad()

            bulletinManager.prepare()
            bulletinManager.presentBulletin(above: self)
        // Do any additional setup after loading the view, typically from a nib.
    }

on running the app the bulletin is not displayed.
error shown is: 

2018-05-12 22:49:55.789917+0530 Bullet[1796:709739] Warning: Attempt to present <BulletinBoard.BulletinViewController: 0x103312770> on <Bullet.ViewController: 0x10330c810> whose view is not in the window hierarchy!

however the bulletin is presented through an IBAction button press successfully 

### Environment

- **iOS Version**: [11.3.1]
- **Device(s)**: [iPhone 6s]

**Comment by alexaubry** [comment]
On iOS, you can usually only present a new view controller if the current view controller is displayed, because otherwise there is no view on the screen to perform the transition. You should try moving this code to `viewDidAppear`.

**Comment by naman17** [comment]
Thank you, makes sense and works fine from `viewDidAppear`
