### ISSUE TITLE
Feature Request: Support for NSAttributedString

### ISSUE THREAD

**Issue by mergesort** [alexaubry/BulletinBoard#75]
### New Issue Checklist

- [x] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Issue Description

I would like to request support for a property called `attributedDescriptionText` in addition to `descriptionText`. The level of effort to add it should be pretty minimal, and it would allow for more customization in the appearance of the text, making the library more flexible to handle other use cases.

I've run into a situation that seems like it would be a good match for this, and would love to see support added.

The hard work is appreciated, and thank you for your consideration!

**Comment by heyhujiao** [comment]
hi I would like to ask why does the NSAttributedString of descriptionLabel not able to open links even though I added the link attributed to the string...?

I even tried adding UITapGestureRecogniser to the string but I still cannot open URLs from the text in the descriptionLabel. Followed [this](https://samwize.com/2016/03/04/how-to-create-multiple-tappable-links-in-a-uilabel/) but still cannot open links from description label.
