### ISSUE TITLE
CloseGlyph - Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by victor-sarda** [alexaubry/BulletinBoard#81]
### New Issue Checklist

- [x] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Issue Description

Hi 👋,
I just installed BulletinBoard 2.0.0 and I get a crash when I'm running my build.
I get `Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value` in BulletinCloseButton.swift, line 50: `let glyph = UIImage(named: "CloseGlyph", in: Bundle(for: BulletinCloseButton.self), compatibleWith: nil)!`.

It looks like the **CloseGlyph** image is missing or something. I tried to set `requiresCloseButton` to **false** in my BLTNPageItem but it didn't change anything...

I looked into the BulletinBoard pod folder in my project and could find the CloseGlyph image.
I can share some code if you need too.

Thanks!

### Environment

- **BulletinBoard Version**: 2.0.0
- **iOS Version**: 11.3
- **Device(s)**: iPhone 7, iPhone X simulator

**Comment by yusuftor** [comment]
I got this issue too... please fix asap

**Comment by alexaubry** [comment]
There was a problem with the Podspec, it didn't include the image resources. Sorry about this issue 😰 

Could you please try if the fix works before I push the hotfix by replacing the BulletinBoard in your Podfile by this (to download from master): 

~~~ruby
pod 'BulletinBoard', :git => 'https://github.com/alexaubry/BulletinBoard.git', :branch => 'master'
~~~

And run `pod update`. Let me know if this fixes your issue.

**Comment by victor-sarda** [comment]
Sure, no problem. I'll try it now

**Comment by victor-sarda** [comment]
Yep it looks like it's fixing it 🎉
Nice update btw 😅

**Comment by alexaubry** [comment]
You can update to `2.0.1` now. Sorry about the inconvenience.

**Comment by a2** [comment]
![High fiving a million angels](https://media.giphy.com/media/DOxlkyuDxTrna/giphy.gif)
