### ISSUE TITLE
How to check whether BLTNItemManager is displaying?

### ISSUE THREAD

**Issue by yusuftor** [alexaubry/BulletinBoard#83]
I can't see a way to tell if the bulletin manager is already displaying an item. This would be super useful in my app if it could be implemented, if not already. Thanks!

**Comment by arvidurs** [comment]
+1

I would like to check if it is displaying, if so dismiss.

**Comment by arvidurs** [comment]
@yusuftor what I did.. I went to the **BLTNItemManager** and changed the var fileprivate var isPrepared to public var isPrepared. Then I was just doing the check if isPrepared { do this}. Which solved my issue

**Comment by arvidurs** [comment]
I'm on cocoa pods too.. I still can just edit it locally. For him to implement it though, I would rather do this:
`public var isShowingBulletin: Bool {
        return isPrepared
    }`

**Comment by yusuftor** [comment]
Do you think you could submit a pull request with that modification?

**Comment by ServusJon** [comment]
please do a pull request @arvidurs :-)

**Comment by alexaubry** [comment]
The `isShowingBulletin` property was added in v3. Thanks for the suggestion!
