### ISSUE TITLE
BulletinManager already created when used inside collectionViewCell

### ISSUE THREAD

**Issue by Leniox** [alexaubry/BulletinBoard#84]
I have a collectionView. Inside each viewCell, I have an image with a tapped gesture closure. When the image is tapped, it fires the bulletin manager. This is important because I am using each collectionviewCell's Image as the page.image for the bulletinpageItem. 

class CollectionViewCell: UICollectionViewCell{
    
    @IBOutlet weak var featuresLabel: UILabel!
    @IBOutlet weak var modelLabel: UILabel!
    @IBOutlet weak var costLabel: UILabel!
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var productImage: UIImageView!
    weak var cellDelegate: YourCellDelegate?
    weak var navigationController: UINavigationController?
    var itemDetailsURL = ""
    var wishListURL = ""
    //this is a class member
    lazy var bulletinManager: BulletinManager! = {
        let page = PageBulletinItem(title: "Select Image")
        page.image = productImage.image
        page.descriptionText = "Would you like to make this picture the gift image?"
        page.actionButtonTitle = "Set Image"
        page.alternativeButtonTitle = "Not now"
        page.actionHandler = { (item: PageBulletinItem) in
            print("Action button tapped")
            let giftDetailsController = self.navigationController?.viewControllers.last as! GiftDetails
            giftDetailsController.setGiftImageFromCell(newImage: self.productImage.image!)
            item.manager?.dismissBulletin(animated: true)
            item.manager?.popItem()

        }
        page.alternativeHandler = { (item: PageBulletinItem) in
            print("Alternative button tapped")
            item.manager?.dismissBulletin(animated: true)
            item.manager?.popItem()

        }

        //            let greenColor = UIColor(red: 0.294, green: 0.85, blue: 0.392, alpha: 1)
        //            page.appearance.actionButtonColor = greenColor
        //            page.appearance.alternativeButtonColor = greenColor
        //            page.appearance.actionButtonTitleColor = .white
        return BulletinManager(rootItem: page)
    }()

....

    
    @objc func tappedImage()
    {
   
        let giftDetailsController = navigationController?.viewControllers.last
        

        bulletinManager.prepare()
        bulletinManager.presentBulletin(above: giftDetailsController!)

    }

However, for some reason, there are cells where the bulletinManager.storage is not nil. By that, I mean if I break where It says "bulletinManager.prepare()", the bulletinManager.storage is not nil. It should be. And it presents with old data. In fact, it does not even just-in-time evaluate the lazy var and thus, I am stuck with an page.image from a previous cell. 

Do you have any ideas on how to ensure that the cell that is displaying corresponds with that bulletin manager?

### New Issue Checklist

- [x] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Environment

- **BulletinBoard Version**: [INSERT LIBRARY VERSION HERE]
- **iOS Version**: [INSERT iOS VERSION HERE]
- **Device(s)**: [INSERT DEVICE(S) HERE]

**Comment by alexaubry** [comment]
Hey, sorry for the late reply. This happens because iOS reuses the cells when you scroll. That means that it wont initialize a new cell object for each item, but rather repurposes a cell that is became off-screen. This is why you see old data.

You should re-create the bulletin manager in `prepareForReuse` method to fix this issue. Let me know if you still need help.

**Comment by alexaubry** [comment]
Closing this issue for now, please reopen if you still need help.
