### ISSUE TITLE
attributedDescriptionText doesn't seem to be working.

### ISSUE THREAD

**Issue by aliondos** [alexaubry/BulletinBoard#89]
### New Issue Checklist

- [x] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Issue Description

This is what I'm doing, or trying to do...
```
let attrString = NSMutableAttributedString(string: "text", attributes: [NSAttributedStringKey.font: UIFont.systemFont(ofSize: 20)])
attrString.append(NSMutableAttributedString(string: "text2", attributes: [NSAttributedStringKey.font: UIFont.systemFont(ofSize: 12)]))
rootItem.attributedDescriptionText = attrString
```

It just displays a bulletin with an empty description whenever I try to use attributed strings.

- **BulletinBoard Version**: [2.0.1]
- **iOS Version**: [11.4]
- **Device(s)**: [SIMULATOR]

**Comment by alexaubry** [comment]
This was fixed by @a2. Thank you for the hint 😄
