### ISSUE TITLE
Pod File not inline with Example

### ISSUE THREAD

**Issue by Danny-SS** [alexaubry/BulletinBoard#9]
### New Issue Checklist

- [x ] I updated BulletinBoard to the latest version.
- [ x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [ x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [ x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

### Issue Description

I was eager to try this framework as it looks great.  I was able to play around the with example yesterday and decided to install it via Pods into my project.  It seems out of date from the Example on GitHub.

Some issues: 

Example #1
There is **no** BulletinBackgroundViewStyle.swift in my installed Pod file

Example #2 
In the BuildManager.swift there is **no**
 `public ivar public var backgroundViewStyle`

I followed the install instructions and have a simple 

`pod 'BulletinBoard'`

[FYI, Instructions should put line in single quotes instead of double quotes]

alongside my other pod files.

### Environment

- **iOS Version**: [INSERT iOS VERSION HERE]
iOS 11
- **Device(s)**: [INSERT DEVICE(S) HERE]
testing in Simulator

**Comment by alexaubry** [comment]
A new version of the Podspec (1.3.0) was released to support the `backgroundViewStyle` property and the latest changes from the demo project. 🚀

You can run `pod update` to get the latest version of the library.

**Comment by Danny-SS** [comment]
Thanks.  Updated and all looks good so far.
