### ISSUE TITLE
WebView Support?

### ISSUE THREAD

**Issue by petritz** [alexaubry/BulletinBoard#93]
Hello,
is it also possible to have WebView Support within a Page?

I tried creating a custom feedback page item and returned a WKWebView (and UIWebView) in the `makeViewsUnderDescription` method but that only results to an empty page being rendered. I followed the example where the UICollectionView is implemented, but still no success.

**Comment by petritzdesigns** [comment]
The newest stable version. I deleted the subclass again, but it was basically the example with the collection view but with the web view. The result displayed just the title, so I guess that there are just layout problems? Although with the UI Debug Tool there was no Web View Node…

**Comment by alexaubry** [comment]
I tried to reproduce it, but it seems to work fine. This is the code I used: https://gist.github.com/alexaubry/173f9abd92af9e782a95d1366bf52cd1

**Comment by alexaubry** [comment]
Please reopen this if this is still an issue.

**Comment by petritz** [comment]
I think I did not specify a height so it got 0
