### ISSUE TITLE
Update for Xcode 10

### ISSUE THREAD

**Issue by Gianlo98** [alexaubry/BulletinBoard#97]
Hi i want to use this library inside my Xcode project but i can't do this because i'm using swit 4.2 and the master branch (installed with pod) use the 4.1 version. 
The library will be updated ?

**Comment by Gianlo98** [comment]
sure ! 
I have 2 errors, one when i'm importing the library and the others on the left
https://www.dropbox.com/s/tldda44ndk0luy1/Screenshot%202018-07-21%2018.38.46.png?dl=0

Maybe i had a mistake when i have installed the library with pod ? 
Thanks for help

**Comment by alexaubry** [comment]
Oh you are using Xcode 10! I will fix the compilation errors. You could also contribute if you feel like it 😃

**Comment by slashmo** [comment]
@Gianlo98 & @alexaubry Is either of you already working on this? Otherwise, I'd like to do it 😊

**Comment by alexaubry** [comment]
@Gianlo98 I didn't start anything yet. Feel free to pick it up :)

**Comment by mbuchetics** [comment]
> The library is written in Swift 3.2 and should be source-compatible with any further Swift version.

Unfortunately, that is not correct. Currently, there is no source-compatibility, even with Swift 4.2.

**Comment by gesabo** [comment]
Any update on compatibility with Xcode 10, Swift 4.2?  I'd like to check out this lib but can't as I'm seeing "no such module BLTNBoard" compiler error.

**Comment by alexaubry** [comment]
v3.0 shipped today with full support of Xcode 10 and Swift 4.2. Thank you for your patience.
